import { Inter } from "next/font/google";
import "./globals.css";
import LayoutProvider from "@/Component/LayoutProvider";
import { ContextProvider } from "@/Component/ContextProvider";
import ServiceContext from "@/Component/ServiceContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
          <ContextProvider>
            <ServiceContext>
            {children}
            </ServiceContext>
            </ContextProvider>
      </body>
    </html>
  );
}
